// Mock events for Phase 1.
// Replace by removing flowStore.seed(MOCK_FLOW_EVENTS) in FlowLayer
// once real emitters are wired.

import { FlowEvent } from "./flow-types";

export const MOCK_FLOW_EVENTS: FlowEvent[] = [
  {
    id:        "evt-001",
    timestamp: "05:41:12",
    agent:     "System",
    type:      "input",
    status:    "complete",
    title:     "Mission Control started",
    detail:    "All panels initialised",
    source:    "host",
    target:    "Phoenix",
  },
  {
    id:        "evt-002",
    timestamp: "05:41:15",
    agent:     "Gateway",
    type:      "routing",
    status:    "complete",
    title:     "OpenClaw ready",
    detail:    "Port 18790",
    source:    "OpenClaw",
    target:    "openrouter/auto",
  },
  {
    id:        "evt-003",
    timestamp: "05:41:21",
    agent:     "Legend",
    type:      "input",
    status:    "complete",
    title:     "Received Discord message",
    detail:    "#legend-creative",
    source:    "Discord",
    target:    "Gateway",
  },
  {
    id:        "evt-004",
    timestamp: "05:41:22",
    agent:     "Gateway",
    type:      "routing",
    status:    "complete",
    title:     "Routed → openrouter/auto",
    detail:    "primary lane selected",
    source:    "Gateway",
    target:    "Phoenix",
  },
  {
    id:        "evt-005",
    timestamp: "05:41:25",
    agent:     "Legend",
    type:      "output",
    status:    "complete",
    title:     "Response generated",
    detail:    "312 tokens",
    source:    "Phoenix",
    target:    "Discord",
  },
  {
    id:        "evt-006",
    timestamp: "05:41:27",
    agent:     "Legend",
    type:      "memory",
    status:    "complete",
    title:     "Qdrant write completed",
    detail:    "namespace: legend",
    source:    "Legend",
    target:    "Qdrant",
  },
  {
    id:        "evt-007",
    timestamp: "05:41:30",
    agent:     "Seraphim",
    type:      "task",
    status:    "waiting",
    title:     "Task created",
    detail:    "Awaiting agent confirmation",
    source:    "Seraphim",
    target:    "Task Queue",
  },
  {
    id:        "evt-008",
    timestamp: "05:41:34",
    agent:     "Elior",
    type:      "memory",
    status:    "complete",
    title:     "TrueRecall archived",
    detail:    "session context saved",
    source:    "Elior",
    target:    "TrueRecall",
  },
  {
    id:        "evt-009",
    timestamp: "05:41:38",
    agent:     "Diamond",
    type:      "repo",
    status:    "active",
    title:     "File write completed",
    detail:    "lib/flow/flow-types.ts",
    source:    "Lucy",
    target:    "mission-control",
  },
  {
    id:        "evt-010",
    timestamp: "05:41:42",
    agent:     "Gateway",
    type:      "routing",
    status:    "queued",
    title:     "Fallback check scheduled",
    detail:    "next: ollama/qwen2.5:7b",
    source:    "Gateway",
    target:    "Lucy",
  },
];
